### ISSUE TITLE
no me descarga el reporte ejecutando newman en el pipeline de jenkins 

### ISSUE THREAD

**Issue by maximilianofni** [postmanlabs/newman-reporter-html#159]
como soluciono este problema 
 1) ejecuto esto en el pipeline
node {
    stage('Prueba git'){
        git 'https://github.com/maximilianofni/prueba.git'
    }
    stage('TestCases-Postman-Newman'){
        bat 'npm install'
        bat 'npm run prueba'
    }
}

2) esto esta escrito en mi package.json

  "name": "prueba222",
  "version": "1.0.0",
  "description": "prueba test grapi ok",
  "version":"0.0.1",
  "private":true,
  "scripts": {
    "prueba": "newman run prueba222.postman_collection.json --reporters=cli,htmlextra --disable-unicode "
  },
  "author": "maxi francesconi",
  "dependencies": {
    "newman": "^4.5.7"
  }
}
 
y me sale esto:
![chrome_2020-02-10_14-40-31](https://user-images.githubusercontent.com/17895688/74174809-61601d80-4c13-11ea-8792-3be8eff44b21.png)

**Comment by DannyDainton** [comment]
Hey @maximilianofni

This is not the `htmlextra` reporter repo.

Also, the reporter is not listed in the dependencies, like you have `newman`, it's probably not installed correctly or in the right location but you're trying to use it in the command.

Could you close this issue and raise one in the correct repository so that I can take a better look please.
