### ISSUE TITLE
Facing trouble in running the newman html reporter, installed newman and also html reporter. but getting this error

### ISSUE THREAD

**Issue by sumabala9** [postmanlabs/newman-reporter-html#230]
Hi,
I am facing this Error while trying to newman html reporter. installed newman and also html reporter but getting this error.

C:\Users\chavali.sumabala\AppData\Roaming\npm>newman run Longwall_Collection -r html
error: EEXIST: file already exists, mkdir 'C:\Users\chavali.sumabala\AppData\Roaming\npm\newman'

Can anyone please help on this .exactly not getting what to do
![newmanissue](https://user-images.githubusercontent.com/65771070/92205439-4ef54c00-eea3-11ea-9ea6-8dc565f9482d.PNG)

**Comment by DannyDainton** [comment]
You will need to run it from a different directory as the html reporter creates a new 'newman' directory to save the report.

There's already a 'newman' directory within 'npm' which is the actual Newman package.

**Comment by sumabala9** [comment]
Yes I tried

> You will need to run it from a different directory as the html reporter creates a new 'newman' directory to save the report.
> 
> There's already a 'newman' directory within 'npm' which is the actual Newman package.

Yes ,I tried running from new directory also. I installed outside from cmd and try to run outside. But problem is it is not running from outside directory. It is always pointing to same path
'C:\Users\chavali.sumabala\AppData\Roaming\npm\newman
From other directory it is showing newman unrecognized eventhough I am installing.
What will be the solution here? Should I need to delete any folder ? What should I do?

**Comment by DannyDainton** [comment]
I would fully uninstall both with this and make sure you copy and paste the same commands:

```
npm uninstall -g newman newman-reporter-html
```

Then install them both again:

```
npm install -g newman newman-reporter-html
```

Navigate to your desktop from the CMD so that the you're completly away from that `npm` directory. 

The run it again with:

```
newman run filepath/collection.json -r cli,html
``` 
If you've followed that correctly, by default, it will create a `/newman` directory and within that will be the html report. 

If you're still getting an error after that, send a screenshot of what you're seeing.

**Comment by sumabala9** [comment]
Hi Danny,
i followed same procedure what u have mentioned, uninstalled ,and again installed ..but it is pointing again to same directory.After installation ,i kept my "collection.json" in other directory and try to run it using newman run "collection.json" -r cli,html . but it is showing newman unrecognized. Please find all the screen-shots which i had attached below for your reference.
And also one thing i want to mention is i had installed cypress,angular before installing newman in same folder, cypress,angular framework
![ImAGE 0](https://user-images.githubusercontent.com/65771070/92320905-dcbb6d80-f042-11ea-8ef8-727064f17035.PNG)
![image1](https://user-images.githubusercontent.com/65771070/92320907-de853100-f042-11ea-988a-01c6092f3dae.PNG)
![image2](https://user-images.githubusercontent.com/65771070/92320908-df1dc780-f042-11ea-9762-436d97a52a9e.PNG)
![image3](https://user-images.githubusercontent.com/65771070/92320909-dfb65e00-f042-11ea-975a-6bfda5c18bdb.PNG)



 also contains npm folder.Whether any conflict is happening for that(Not sure exactly).Please find screen-shots below
Screen-shots are in reverse order,but i followed process in proper order only.

**Comment by DannyDainton** [comment]
From the order of your screenshots it looks like you installed it and then uninstalled. Then used the -v command after the install and the version showed so that feels like it wasn't uninstalled. 

Can you be clear and put things in the correct order please. It's quite important when explaining something to other people 😁

Navigate to the new directory before doing the uninstall, followed by the install. Your collection file will need to be in either the new directory that you're running it from or use the full file path to to collection file.

This is the most basic way that newman and the reporter can be used so there's no more 'solutions' other than ensuring that the PATH to node is correct.

**Comment by sumabala9** [comment]
> From the order of your screenshots it looks like you installed it and then uninstalled. Then used the -v command after the install and the version showed so that feels like it wasn't uninstalled.
> 
> Can you be clear and put thing in the correct order please.
> 
> Navigate to the new directory before doing the uninstall, followed by the install. Your collection file will need to be in either the new directory that you're running it from or use the full file path to to collection file.
> 
> This is the most basic way that newman and the reporter can be used so there's no more 'solutions' other than ensuring that the PATH to node is correct.

Ok thanks for your reply. Will try the above .

**Comment by DannyDainton** [comment]
Seems like you have that working. 🏆

Now is the best time to suggest that you use a different html reporter:

https://github.com/DannyDainton/newman-reporter-htmlextra

😁
